sudo: required

language: cpp

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - git clone https://github.com/DiligentGraphics/DiligentCore.git ../DiligentCore --recursive
  - . ../DiligentCore/BuildTools/Scripts/travis/before_install.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake

matrix:
  include:
  - os: linux
    compiler: gcc
    env: CONFIG=Release
  - os: osx
    osx_image: xcode11.1
    compiler: clang
    env:
      - CONFIG=Release
      - IOS=false
  - os: linux
    compiler: gcc
    env: CONFIG=Debug
  - os: osx
    osx_image: xcode11.1
    compiler: clang
    env: 
      - CONFIG=Release
      - IOS=true

script:

  - cd ./BuildTools/FormatValidation
  - . ../../../DiligentCore/BuildTools/Scripts/travis/validate_format.sh
  - cd ../../..
  - |
    echo "cmake_minimum_required(VERSION 3.6)" > CMakeLists.txt
    echo "Project(DiligentTools_Test)" >> CMakeLists.txt
    echo "add_subdirectory(DiligentCore)" >> CMakeLists.txt
    echo "add_subdirectory(DiligentTools)" >> CMakeLists.txt
  - . ./DiligentCore/BuildTools/Scripts/travis/build_install.sh "-DDILIGENT_BUILD_TESTS=TRUE"
  - cd ../DiligentTools/Tests/DiligentToolsTest/assets
  - . ../../../BuildTools/Scripts/travis/run_tests.sh ../../../../build/DiligentTools
  - cd ../../../..

after_success:

  - cd ./build/install
  - export ZIP_NAME=DiligentTools-${TRAVIS_OS_NAME}-${GLSLANG_BUILD_TYPE}.zip;
  - zip -r ${ZIP_NAME} .
