name: Emscripten

on: [push, pull_request]

env:
  emscripten_version: "2.0.30"

jobs:
  build-win10:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: windows-latest
    name: Windows 10 -> Emscripten, ${{ matrix.config }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download and Configure Emscripten SDK
      uses: mymindstorm/setup-emsdk@master
      with:
        version: ${{env.emscripten_version}}
      
    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "emscripten" "${{runner.workspace}}" ${{ matrix.config }} "-DDILIGENT_BUILD_CORE_TESTS=ON"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . -j2

  build-linux:
    strategy:
      matrix:
        config: [Debug, Release]

    runs-on: ubuntu-latest
    name: Linux -> Emscripten, ${{ matrix.config }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
       
    - name: Configure Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download and Configure Emscripten SDK
      uses: mymindstorm/setup-emsdk@master
      with:
        version: ${{env.emscripten_version}}

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        chmod +x configure_cmake.sh
        ./configure_cmake.sh "emscripten" "${{runner.workspace}}" ${{ matrix.config }} "-DDILIGENT_BUILD_CORE_TESTS=ON"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . -j2

  build-macos:
    strategy:
      matrix:
        config: [Debug]

    runs-on: macos-latest
    name: MacOS -> Emscripten, ${{ matrix.config }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download and Configure Emscripten SDK
      uses: mymindstorm/setup-emsdk@master
      with:
        version: ${{env.emscripten_version}}

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        chmod +x configure_cmake.sh
        ./configure_cmake.sh "emscripten" "${{runner.workspace}}" ${{ matrix.config }} "-DDILIGENT_BUILD_CORE_TESTS=ON"

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . -j2
