name: Trigger Build Web Page

on:
  workflow_run:
    workflows: ["Build Emscripten"]
    types:
      - completed

jobs:
  send-notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'master' }}
    steps:
      - name: Send notification to DiligentGraphics.github.io
        env:
          TARGET_REPO_TOKEN: ${{ secrets.PAGES_BUILD_AND_DEPLOY }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TARGET_REPO_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/DiligentGraphics/DiligentGraphics.github.io/dispatches \
            --data '{ "event_type": "rebuild-wasm-modules" }'
